In [8]:
#Import Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
# read files
diversity = pd.read_csv('/content/drive/MyDrive/new_diversity.csv')
salary_potential = pd.read_csv('/content/drive/MyDrive/salary_potential.csv')
tuition = pd.read_csv('/content/drive/MyDrive/tuition.csv')

In [10]:
# merge dataset
college = diversity.merge(right = salary_potential, on = 'name').merge(right = tuition, on = 'name')
college['degree_length'].unique()

array(['4 Year'], dtype=object)

In [11]:
college

,Unnamed: 0,name,total_enrollment,state_x,race/ethnicity,enrollment,women_proportion,rank,state_name,early_career_pay,mid_career_pay,make_world_better_percent,stem_percent,state_y,type,degree_length,net_cost,income_lvl
0,70,University of Central Florida,60767,Florida,American Indian / Alaska Native,120,0.550990,16,Florida,49700,88600,50.0,16,Florida,Public,4 Year,9318.00,"0 to 30,000"
1,70,University of Central Florida,60767,Florida,American Indian / Alaska Native,120,0.550990,16,Florida,49700,88600,50.0,16,Florida,Public,4 Year,10869.00,"30,001 to 48,000"
2,70,University of Central Florida,60767,Florida,American Indian / Alaska Native,120,0.550990,16,Florida,49700,88600,50.0,16,Florida,Public,4 Year,13641.00,"48_001 to 75,000"
3,70,University of Central Florida,60767,Florida,American Indian / Alaska Native,120,0.550990,16,Florida,49700,88600,50.0,16,Florida,Public,4 Year,15495.00,"75,001 to 110,000"
4,70,University of Central Florida,60767,Florida,American Indian / Alaska Native,120,0.550990,16,Florida,49700,88600,50.0,16,Florida,Public,4 Year,15761.00,"Over 110,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279811,19398,Bloomfield College,2004,New Jersey,Non-Resident Foreign,70,0.637725,23,New-Jersey,48400,89100,55.0,17,New Jersey,Private,4 Year,17793.17,"0 to 30,000"
279812,19398,Bloomfield College,2004,New Jersey,Non-Resident Foreign,70,0.637725,23,New-Jersey,48400,89100,55.0,17,New Jersey,Private,4 Year,18925.68,"30,001 to 48,000"
279813,19398,Bloomfield College,2004,New Jersey,Non-Resident Foreign,70,0.637725,23,New-Jersey,48400,89100,55.0,17,New Jersey,Private,4 Year,21498.06,"48_001 to 75,000"
279814,19398,Bloomfield College,2004,New Jersey,Non-Resident Foreign,70,0.637725,23,New-Jersey,48400,89100,55.0,17,New Jersey,Private,4 Year,25865.12,"75,001 to 110,000"
279815,19398,Bloomfield College,2004,New Jersey,Non-Resident Foreign,70,0.637725,23,New-Jersey,48400,89100,55.0,17,New Jersey,Private,4 Year,27991.93,"Over 110,000"

In [ ]:
college.to_csv('/content/drive/My Drive/college.csv', index=False)

In [ ]:
#college = college[college['state'] == 'Massachusetts']
#college